apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata:
  name: hello-world-svc
  labels:
    name: hello-world-svc
spec:
  ports:
    - port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
      protocol: TCP
      nodePort: 31000
  selector:
    app: hello-world-svc
  type: NodePort # type of the service. LoadBalancer indicates that our service will be external.
